[package]
name = "byte_struct"
version = "0.1.0"
authors = ["Weiyi Wang <wwylele@gmail.com>"]
edition = "2018"

[dependencies]
byte_struct_derive = { version = "0.1.0", path = "../byte_struct_derive" }

[dev-dependencies]
